---
name: test
on:
  pull_request:
  push:
    branches:
    - main
env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: pre-commit/action@v2.0.3
    - run: cmake -B build
    - run: cmake --build build --verbose
