---
name: test
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  pre-commit:
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: pre-commit/action@v2.0.3
