---
name: test
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: pre-commit/action@v2.0.3
    - run: cmake -B build
    - run: cmake --build build --verbose
